services:
  backend-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/bus-ticketing-app
    depends_on:
      - db

  frontend-dev:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:5000

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: